### ISSUE TITLE
Favourite

### ISSUE THREAD

**Issue by Zorooo4i** [Xwilarg/NHentaiDownloader#12]

**Comment by Xwilarg** [comment]
Hi,

I'm not sure what you mean by "favourite", could you please explain what you need or what is the issue?

**Comment by Zorooo4i** [comment]
> Hi,
> 
> I'm not sure what you mean by "favourite", could you please explain what you need or what is the issue?

sorry .  I thought that this button will add your repository to the favorites folder where I can then find and download it, as in telegram

**Comment by Xwilarg** [comment]
Ah no problem, thanks for your support!
