### ISSUE TITLE
Firefox Support??

### ISSUE THREAD

**Issue by BluetoDark** [Xwilarg/NHentaiDownloader#14]
It is not hard too port it over too firefox only for some wierd thing it maybe is not

**Comment by Xwilarg** [comment]
The extension is already available on Firefox, I updated the explanations on the README: https://github.com/Xwilarg/NHentaiDownloader#firefox

**Comment by BluetoDark** [comment]
> 
> 
> The extension is already available on Firefox, I updated the explanations on the README: https://github.com/Xwilarg/NHentaiDownloader#firefox

I'm blind and stupid
