### ISSUE TITLE
For firefox users! (proper install) 

### ISSUE THREAD

**Issue by BluetoDark** [Xwilarg/NHentaiDownloader#15]
**If you are on firefox and you want too install the add-on permanently you should do the following. If u use the "about:debugging#/runtime/this-firefox" method it will not be installed permanently and you will need too add it on every restart of firefox.**

1. go too "about:config" (in the search bar ofc) then search for "xpinstall.signatures.required" and set it too false.
2. Download the latest version on github with the manifest_firefox.json (the zipped release does not have this).
3. Unzip and replace manifest.json with manifest_firefox.json (make sure u replace/rename it too the manifest.json and not manifest_firefox.json!!)
4. Zip the fire back too NHentaiDownloader.zip then rename it too NHentaiDownloader.xpi
5. Drag the file into "about:addons" (aka. your add-on page in settings) and there you go you have it.

_Bonus.... If you go down in too the settings of the extension you can allow it too run in private window (just like every other extension)._

_I hope the creator will add  this installation guide instead of the other and maybe include the xpi file in releases._
_I have tested this on Firefox Firefox Developer edition Firefox nightly and on Linux Firefox_

**Comment by Xwilarg** [comment]
Thanks for your issue, I however would like to have more information about this before updating the README, do you have an error with the current process?
I tried the old steps with Firefox Stable Version (89.0.1) and Developer Version (90.0b.10) and everything is working fine for me

**Comment by Xwilarg** [comment]
Looks like unsigned extensions no longer work after Firefox 44: https://support.mozilla.org/en-US/questions/1101877

**Comment by Xwilarg** [comment]
I managed to sign the extension and updated the guide in the README, feel free to reopen this if needed
