### ISSUE TITLE
An unexpected error occured: Code 0

### ISSUE THREAD

**Issue by L1so** [Xwilarg/NHentaiDownloader#16]
It used to work nicely, but since yesterday when I tried to download something, instead of a download button it will display this error.

> An unexpected error occured: Code 0

My browser is Opera 78.0.4093.112 (latest version), and as the site is blocked here, I always use built-in vpn from Opera to bypass. I can confirm the issue is not my net as I can browse the library freely.

Though this only happen on private browsing mode, in normal mode the download button should appear after a while, but what strange is, it took a longer time than usual to download a book. For example before I can complete the download in just 30 second for 20 pages book, but now it took 5 minutes just to complete 10 pages book.

**Comment by Xwilarg** [comment]
Hi, thanks for the bug report
I wasn't able to reproduce the issue on Chrome so I'll download Opera to see if it's specific to this browser

On the sideline, are you sure that the issue isn't related to your Internet connection? (that seems to be the case seeing the description of the issue)
I don't really know how Opera VPN work but did you try to connect to another region before downloading?

**Comment by L1so** [comment]
> Hi, thanks for the bug report
> I wasn't able to reproduce the issue on Chrome so I'll download Opera to see if it's specific to this browser
> 
> On the sideline, are you sure that the issue isn't related to your Internet connection? (that seems to be the case seeing the description of the issue)
> I don't really know how Opera VPN work but did you try to connect to another region before downloading?

There was three region offered on Opera VPN, and I have tried all of them to no avail, the result is still the same. Note that it only affect private browsing mode, in default mode I can download normally without issues, though it takes longer time like I said in my previous post.

My internet works fine, I can open any sites with or without VPN on, the manga load normally without issues.

**Comment by Xwilarg** [comment]
Um... I downloaded latest Opera version and I didn't have any issue on it
If you go on the extension page, is there any error displayed there?

**Comment by L1so** [comment]
There was no error displayed on the extension page, like I said it used to work perfectly fine.

![Peek 2021-08-10 10-02](https://user-images.githubusercontent.com/44594524/128802307-97897e41-1b09-4bd1-a4d8-68a82957fccf.gif)

This is what happen when I tried to download something.

**Comment by Xwilarg** [comment]
Can you please do a right click on the popup and click on "Inspect" and tell me if there is anything in the "Console" tab?

**Comment by L1so** [comment]
Hello ! Sorry for late response.

I just look into the console page that you mentioned, weirdly I dont see anything at all, it just a blank white. Should I tried reinstalling the plugin ?

**Comment by Xwilarg** [comment]
White page is default behaviour so it's okay
I will probably go back on the extension this week-end to clean and add some diagnostics tools in the code, I'll keep you updated when it'll be done, thanks for your patience!

**Comment by Xwilarg** [comment]
I did some improvements on the code, can you please tell me if the error messages gives you more information:
[NHentaiDownloader.zip](https://github.com/Xwilarg/NHentaiDownloader/files/6988116/NHentaiDownloader.zip)

**Comment by L1so** [comment]
Hi ! Again, really sorry for late response.

I just tried your new extension, it doesn't spurt any error message, but I see new message from the "Inspect Element" tab like you suggested.

![screenshot05](https://user-images.githubusercontent.com/44594524/129697788-6404e377-66d3-4f8c-bc17-865f99cd0086.jpg)

`Failed to load resource: net::ERR_CONNECTION_RESET`

This error seems suggest that there was a connection issue, the problem is the connection works fine. However, this behavior is not occurring on normal mode (non private browsing), I can downloads just fine on normal mode.

Thanks for your hard work ! I really appreciate it :+1:

**Comment by Xwilarg** [comment]
Hi, if you go on the page to manage extension and press "Examine background page", the console is still empty there?

**Comment by L1so** [comment]
> Do you think you could delete your cookies for this website as described [here](https://stackoverflow.com/a/42482828) to be sure this isn't the issue?

After doing this, surprisingly the download works without issue, gonna keeping you in touch for further issue. Thanks !
