### ISSUE TITLE
Bad download performances

### ISSUE THREAD

**Issue by Xwilarg** [Xwilarg/NHentaiDownloader#19]
### Discussed in https://github.com/Xwilarg/NHentaiDownloader/discussions/18

<div type='discussions-op-text'>

<sup>Originally posted by **tylerthafudd** August 29, 2021</sup>
is there a way to increase the download speed of your program because it seems it be downloading at a rate of 1/2 mbps but my internet can support up to 14 mbps. even after 2 hours of downloading i can only seem to get 1 page out of 40. at this rate its going to be days before its done. by page i mean the 25 doujin that are loaded when searching for a tag.i tried deleting the nhentai's cookies but to no avail unless my IP has been flagged the only thing i could think of it may be the program having some sort low internal download speed. some user control over the download rate would be greatly apricated.</div>

**Comment by tylerthafudd** [comment]
after not downloading all day when i started it back up i was able to download 3 pages after 30 minuets it seems to be running faster. the internet speed also seems yo-yo between taking a full second to download a single image to getting through 4 with in that time.

**Comment by tylerthafudd** [comment]
after not downloading all day when i started it back up i was able to download 3 pages after 30 minuets it seems to be running faster. the internet speed also seems yo-yo between taking a full second to download a single image to getting through 5 with in that time.

**Comment by Xwilarg** [comment]
I'm not sure why it's doing that but I began a redesign of the whole code, hopefully this will help.
If it don't, maybe I'll introduce a feature where the user can start a backend and the download will be done from there

**Comment by Xwilarg** [comment]
Hey,
I rewrote the code of the extension, could you tell me if that improved the performances on your side?
If not I have others plans for that but that'll need some time to add them

**Comment by tylerthafudd** [comment]
sorry it to so long to respond but the new version is fully utilizing my internet speed. honestly im hitting download speeds i thought impossible. using the multiple download nets the same performance as the default feature . i imagined the multiple download would work by downloading multiple files at once instead just splitting each doujin into its own separate zip. i miss the download all option cause now after each page after searching for a tag i got to the start the next one a couple minuets afterwords and then again and again and again making searching for tags with more than 200 doujin take much longer then the older versions.

**Comment by Xwilarg** [comment]
Thanks for the feedback, I'll add an option so multiple download can get them all at once instead of waiting.

I'm however not sure to understand what you mean with the "download all" option.

**Comment by tylerthafudd** [comment]
in the older version you could spedfy down pages 1-900 when searching for a tag or 40-45

**Comment by Xwilarg** [comment]
Are you speaking about this options?
![image](https://user-images.githubusercontent.com/20053454/134007062-5202de05-1f23-43dc-9dce-5849cbccb491.png)
It's still there for me

**Comment by tylerthafudd** [comment]
yeah that

**Comment by tylerthafudd** [comment]
let me turn off add blocker and clear some cookies see if that helps

**Comment by Xwilarg** [comment]
Closing the issue since this is fixed
