### ISSUE TITLE
Can't find the downloaded files (Windows)

### ISSUE THREAD

**Issue by meatball-san** [Xwilarg/NHentaiDownloader#26]
**Firefox Version Windows 10**
When it downloads the files, it says download complete. But when I go to check "downloads", it shows nothing; as if it never downloaded the file.

**Comment by Xwilarg** [comment]
Related to #20 

Somehow ZIP download is broken on Firefox, I identified the issue in the code but I'm not sure how to fix it yet, I'll keep you updated if I manage to solve it

**Comment by Xwilarg** [comment]
The issue should now be fixed, please tell me if it works for you
https://github.com/Xwilarg/NHentaiDownloader/releases/tag/v2.1.4

**Comment by Xwilarg** [comment]
Closing this since the issue is fixed since 7 days, feel free to reopen if needed
