### ISSUE TITLE
Failed to load extension

### ISSUE THREAD

**Issue by MrChicken07** [Xwilarg/NHentaiDownloader#78]
**Failed to load unpacked on operagx**
Whenever i tried to load unpacked it keeps saying failed

![image_2024-10-17_200242961](https://github.com/user-attachments/assets/d8104f4d-0b1a-46ca-a8af-c957fabdcb02)

**Comment by MrChicken07** [comment]
> Hey, did you went on https://github.com/Xwilarg/NHentaiDownloader/releases/tag/v2.1.8 and clicked on NHentaiDownloader.zip/xpi? (and not on Source Code)

i clicked the "Source code (zip)" and it downloaded "NHentaiDownloader-2.1.8".

**Comment by Xwilarg** [comment]
That's the issue then, Source code contains the raw source before some process that make the extension usable

You need to use NHentaiDownloader.zip if you are on Chrome and NHentaiDownloader.xpi if you are on Firefox

**Comment by teh831** [comment]
I facing the same issues on v2.1.9 recently and it seen to be the js folder is missing

Does the folder created itself when load unpack? 
I resolve it by copy one of the older version js folder to the latest one and it work afterward.
