### ISSUE TITLE
Cannot download because NHentai serving .webp images

### ISSUE THREAD

**Issue by internetofshiz** [Xwilarg/NHentaiDownloader#79]
Hi,

I've been having issues getting nhentai downloader to work in the last week or so and after some debugging, I've determined it's because NHentai is now serving webp images and the extension expects jpg, png, or gif.

In /src/background/Downloader.ts in the #downloadPageInternalAsync function, there needs to be a new "w" case for ".webp".

After that, the extension works correctly again.

I'm not sure how pull requests work, so I unfortunately haven't submitted any code, but I thought I would report my findings.

**Comment by Xwilarg** [comment]
I fixed it with release [2.1.9](https://github.com/Xwilarg/NHentaiDownloader/releases/tag/v2.1.9), thanks!
